[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "redsolid"
version = "0.1.0"
description = "Reusable Python libraries, utilities, and tools for software development."
readme = "README.md"
requires-python = ">=3.12"
license = "MIT"
authors = [
    { name = "Brian D. Wilson" }
]

classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[project.urls]
Homepage = "https://github.com/octiforce/public"
Repository = "https://github.com/octiforce/public/tree/main/python/redsolid"
Issues = "https://github.com/octiforce/public/issues"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.pydocstyle]
convention = "pep257"

[tool.ruff]
line-length = 79

[tool.ruff.lint]
select = [
    "E",      # pycodestyle errors
    "W",      # pycodestyle warnings
    "F",      # Pyflakes
    "I",      # isort
    "UP",     # pyupgrade
    "B",      # flake8-bugbear
    "SIM",    # flake8-simplify
    "PIE",    # flake8-pie
    "RET",    # flake8-return
    "RUF",    # Ruff-specific rules
    "W505",   # docstring/comment line length
]

[tool.ruff.lint.pycodestyle]
max-doc-length = 72

[dependency-groups]
dev = [
    "build",
    "mypy",
    "pycodestyle",
    "pydocstyle",
    "pylint",
    "pytest>=9.1",
    "pyright",
    "ruff"
]
