[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "redsolid"
version = "0.1.0"
description = "Reusable Python libraries, utilities, and tools for software development."
requires-python = ">=3.12"
license = "MIT"
authors = [
    { name = "Brian D. Wilson" }
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]

[dependency-groups]
dev = [
    "pytest>=9.1",
    "pyright",
    "pylint",
    "pydocstyle",
]
